### PR TITLE
Add initial Python SDK implementation

### PR DESCRIPTION
**Pull request by gabriela-yoncheva**
... based on Hono (over MQTT) that covers the key Ditto aspects:

Ditto models - Things, Features and entity identification
Ditto protocol abstractions - Envelopes, Topics, Payloads
Ditto protocol Things group support - messages/commands/events
It also provides the means needed for Hono specifics for Command & Control, Telemetry/Events handling

Signed-off-by: gabriela-yoncheva <external.Gabriela.Yoncheva@bosch.io>

### CODE REVIEW

**Comment by thjaeckle** [comment]
@gabriela-yoncheva thank you for your contribution 👍 
Could you please add a signature to all of your commits (also the merge commit)?
Otherwise, the ECA tool checker won't mark this PR as "green".

Commit https://github.com/eclipse/ditto-clients-python/pull/1/commits/054e1b2bd1aaea1b4df23873139bd1c9467c8b0a also contains strange characters in the "Sign-Off" footer's email-address ..

**Comment by thjaeckle** [comment]
Once correctly signed-off, this PR will require a CQ at the Eclipse Foundation as the contribution is > 1.000 lines of code

**Comment by thjaeckle** [comment]
Alreday created CQ: https://dev.eclipse.org/ipzilla/show_bug.cgi?id=23511

@gabriela-yoncheva please fix the sign-off signatures in your commits, otherwise we won't be able to merge this PR.

**Comment by gabriela-yoncheva** [comment]
@thjaeckle The sign-off signatures in the commits have been fixed and all checks have passed

**Comment by thjaeckle** [comment]
CQ was approved yesterday 👍

**Pull request merged**
